#!/bin/sh

#!/bin/sh

case "$1" in 
    start)
        echo "Loading drivers..."
        scull_load
        module_load faulty
        modprobe hello
        echo "Drivers were loaded successfully"
        ;;
    stop)
        echo "Unloading scull, faulty, and hello"
        scull_unload
        module_unload faulty
        rmmod hello || exit 1
        echo "Drivers were unloaded successfully"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0